<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="KaardiManguProject.ApplicationServices\bin\**" />
    <Compile Remove="KaardiManguProject.Core\bin\**" />
    <Compile Remove="KaardiManguProject.Data\bin\**" />
    <Content Remove="KaardiManguProject.ApplicationServices\bin\**" />
    <Content Remove="KaardiManguProject.Core\bin\**" />
    <Content Remove="KaardiManguProject.Data\bin\**" />
    <EmbeddedResource Remove="KaardiManguProject.ApplicationServices\bin\**" />
    <EmbeddedResource Remove="KaardiManguProject.Core\bin\**" />
    <EmbeddedResource Remove="KaardiManguProject.Data\bin\**" />
    <None Remove="KaardiManguProject.ApplicationServices\bin\**" />
    <None Remove="KaardiManguProject.Core\bin\**" />
    <None Remove="KaardiManguProject.Data\bin\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\CardGame.png" />
    <None Include="wwwroot\js\Index.js" />
    <None Include="wwwroot\js\index.scss" />
  </ItemGroup>

  <ItemGroup>      	<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.61.3" />
  </ItemGroup>

</Project>
